services:
  - type: web
    name: cicada-3301-discord-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: LAVALINK_URI
        sync: false
      - key: LAVALINK_PASSWORD
        value: youshallnotpass

  - type: web
    name: cicada-lavalink-server
    runtime: docker
    dockerfilePath: lavalink/Dockerfile
    dockerContext: lavalink
    plan: free
    envVars:
      - key: PORT
        value: 2333
