services:
  - type: web
    name: kyro-discord-bot
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python src/main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: LAVALINK_URI
        value: http://fi15.bot-hosting.net:26267
      - key: LAVALINK_PASSWORD
        value: NfJXUsGSO4tVI1LDl7v3XPYZ
