server:
  port: 26267
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "NfJXUsGSO4tVI1LDl7v3XPYZ"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: false
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 1500
    frameBufferDurationMs: 4000
    opusEncodingQuality: 7
    resamplingQuality: MEDIUM
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: false
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - ANDROID_TESTSUITE
      - TVHTML5EMBEDDED
    oauth:
      enabled: true
      skipInitialization: true
