server:
  port: 26267
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "NfJXUsGSO4tVI1LDl7v3XPYZ"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 4000
    frameBufferDurationMs: 8000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: false

plugins:
  lavasrc:
    providers:
      - "dzisrc:%ISRC%"
      - "dzsearch:%QUERY%"
      - "scsearch:%QUERY%"
    sources:
      spotify: false
      applemusic: false
      deezer: true
      yandexmusic: false
      flowerytts: false
      youtube: false
    deezer:
      masterDecryptionKey: "e82d39e68c7d79201632472d57d7fa45"

  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5EMBEDDED
      - MUSIC
    oauth:
      enabled: true
      skipInitialization: true
